services:
  mariadb_test:
    build: test/acceptance/mariadb/container
    volumes:
      - .:/usr/src/unixodbc
    environment:
      DB_HOST: mariadb
    depends_on:
      mariadb:
        condition: service_healthy
    command: go test -count 1 -race -coverpkg=./... -coverprofile=./test/acceptance/mariadb/coverage.out -tags acceptance ./test/acceptance/mariadb

  mariadb:
    image: "mariadb:10.9-jammy"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_TCP_PORT: 3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=test
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  postgres_test:
    build: test/acceptance/postgres/container
    volumes:
      - .:/usr/src/unixodbc
    environment:
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: go test -count 1 -race -coverpkg=./... -coverprofile=./test/acceptance/postgres/coverage.out -tags acceptance ./test/acceptance/postgres

  postgres:
    image: "postgres:16-bookworm"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      PGUSER: postgres
    healthcheck:
      test: pg_isready
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  mssql_test:
    build: test/acceptance/mssql/container
    volumes:
      - .:/usr/src/unixodbc
    environment:
      DB_HOST: mssql
    depends_on:
      mssql:
        condition: service_healthy
    command: go test -count 1 -race -coverpkg=./... -coverprofile=./test/acceptance/mssql/coverage.out -tags acceptance ./test/acceptance/mssql


  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Acceptance!
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT @@version" || exit 1
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 55