version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: test
      MARIADB_PASSWORD: test
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
    ports:
      - "3306:3306"
  mariadb-tests:
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: acceptance/mariadb/Dockerfile
    environment:
      UPDATE_GOLDEN: false
  mariadb-snapshots:
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: acceptance/mariadb/Dockerfile
    environment:
      UPDATE_GOLDEN: true
    volumes:
      - ./acceptance/mariadb/testdata:/usr/src/app/acceptance/mariadb/testdata