name: Acceptance Tests
on: [push]
jobs:
  mariadb_test:
    name: MariaDB Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run acceptance tests
        run: docker compose run --rm mariadb_test
  postgres_test:
    name: Postgres Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run acceptance tests
        run: docker compose run --rm postgres_test
  mssql_test:
    name: MSSQL Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run acceptance tests
        run: docker compose run --rm mssql_test