name: Go
on: [push]
jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...        

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v .
  mariadb_test:
    name: MariaDB Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run acceptance tests
        run: docker compose run --rm mariadb_test
  postgres_test:
    name: Postgres Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run acceptance tests
        run: docker compose run --rm postgres_test